export const TYPES = {
	Application: Symbol.for("Application"),
	ILogger: Symbol.for("ILogger"),
	UserController: Symbol.for("UserController"),
	ExeptionFilter: Symbol.for("ExeptionFilter"),
	UserService: Symbol.for("UserService"),
	ConfigService: Symbol.for("ConfigService"),
	PrismaService: Symbol.for("PrismaService"),
	UsersRepository: Symbol.for("UsersRepository"),
	AuthMiddleware: Symbol.for("AuthMiddleware"),
	IAdminService: Symbol.for("IAdminService"),
	IAdminController: Symbol.for("IAdminController"),
	IheadOfWarehouseController: Symbol.for("IheadOfWarehouseController"),
	IheadOfWarehouseService: Symbol.for("IheadOfWarehouseService"),
};
